# Generated by Django 2.1.7 on 2019-10-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RenterAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(blank=True, null=True)),
                ('rented_warehouse', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'renter_account',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RentOrder',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rent_order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('root', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.IntegerField(primary_key=True, serialize=False)),
                ('warehouse_name', models.CharField(blank=True, max_length=150, null=True)),
                ('warehouse_size', models.IntegerField(blank=True, null=True)),
                ('warehouse_desc', models.CharField(blank=True, max_length=254, null=True)),
                ('warehouse_image', models.CharField(blank=True, max_length=255, null=True)),
                ('warehouse_price', models.FloatField(blank=True, null=True)),
                ('warehouse_category', models.CharField(blank=True, max_length=150, null=True)),
                ('warehouse_isavailable', models.IntegerField(blank=True, db_column='warehouse_isAvailable', null=True)),
                ('warehouse_currentowenr_use_id', models.IntegerField(blank=True, null=True)),
                ('current_password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'warehouse',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='renteraccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='renter.User'),
        ),
    ]
